### PR TITLE
Add option for passing in a subfolder of the repo to build into

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
This PR introduces a new command flag and option that allows one to define a subfolder of the specified git repo that the drupal site should be built into.

### CODE REVIEW

**Comment by chasingmaxwell** [comment]
Passes code review. Going on to functional now.

**Comment by chasingmaxwell** [comment]
So two things happened after running a deployment where a subfolder was specified:
1. I have a sites/ directory at my project root now. It is definitely an artifact of the deployment.
2. The custom modules, features, and themes directories are missing from my deployed build in the subfolder.

It looks like all the custom modules and themes were just copied to the wrong place during deployment.

**Comment by patrickocoffeyo** [comment]
@chasingmaxwell noted! This is a problem with the Aquifer build system. I shall resolve this problem

**Comment by patrickocoffeyo** [comment]
With the closing of https://github.com/aquifer/aquifer/pull/60, this is ready for re-testing

**Comment by chasingmaxwell** [comment]
This is good to go!

**Pull request merged**
