### PR TITLE
Upgrade nodegit to 0.11.0.

### PR DESCRIPTION
**Pull request by thebruce**
PR to merge in 0.11.0 nodegit upgrade

### CODE REVIEW

**Comment by generalredneck** [comment]
Worked for me.

**Comment by mattgrill** [comment]
@thebruce @generalredneck One thing we might want to consider is setting these version numbers explicitly. Removing the ability to get a compatible version might reduce problems with dependencies. Additionally we can use `shrinkwrap` to lock dependencies.

**Comment by chasingmaxwell** [comment]
@mattgrill working on adding shrinkwrap right now.

**Comment by chasingmaxwell** [comment]
Okay, I'm shipping this.

**Comment by mattgrill** [comment]
@chasingmaxwell One thing that will still cause this to behave oddly is the `^` on versions. We'd probably want to remove that to keep exact version dependencies, making shrinkwrap more useful.

**Comment by chasingmaxwell** [comment]
@mattgrill, my understanding is that even with the `^`, `npm install` will continue to use the specific versions in the npm-shrinkwrap.json file unless you run `npm install --save <package name>`. Is that not true?

**Comment by mattgrill** [comment]
I think you probably want `--save --save-exact mymodule@myversion`

**Comment by mattgrill** [comment]
The shrinkwrap should prevent those compatible versions from being installed, but I'd just like to lock this stuff in and prevent a dependency breakage.

**Comment by chasingmaxwell** [comment]
Just so it's recorded here. @mattgrill and I discussed this and the current shrinkwrap implementation is good for now.

**Pull request merged**
